# Generated by Django 4.2.7 on 2023-12-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("email", models.EmailField(max_length=255, unique=True, verbose_name="Эл. почта")),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="Имя")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_admin", models.BooleanField(default=False, verbose_name="Админ")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Зарегистрирован")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлен")),
                ("is_verified", models.BooleanField(default=False, verbose_name="Подтвержден")),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
