# Generated by Django 4.2.7 on 2024-02-13 20:43

import bood_account.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bood_account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(max_length=60, unique=True, verbose_name="Эл. почта"),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(
                max_length=30, validators=[bood_account.validators.validate_name_field], verbose_name="Имя"
            ),
        ),
    ]
