# Generated by Django 4.2.7 on 2023-12-07 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bood_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(db_index=True, max_length=255, unique=True, verbose_name="Название")),
                ("description", models.TextField(blank=True, default="", verbose_name="Описание")),
                ("image", models.URLField(blank=True, default="", verbose_name="Изображение")),
            ],
            options={
                "verbose_name": "Категория продуктов",
                "verbose_name_plural": "Категории продуктов",
            },
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={"verbose_name": "FAQ", "verbose_name_plural": "FAQ"},
        ),
        migrations.RemoveField(
            model_name="personcard",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="personcard",
            name="preferences",
        ),
        migrations.AddField(
            model_name="personcard",
            name="exclude_products",
            field=models.ManyToManyField(
                blank=True, related_name="personcard", to="bood_app.product", verbose_name="Исключенные продукты"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(max_length=255, verbose_name="Вопрос"),
        ),
        migrations.AlterField(
            model_name="personcard",
            name="femaletype",
            field=models.ManyToManyField(
                blank=True, related_name="personcard", to="bood_app.femaletype", verbose_name="Тип женщины"
            ),
        ),
        migrations.AlterField(
            model_name="personcard",
            name="target",
            field=models.CharField(
                blank=True,
                choices=[("lose", "Похудение"), ("keep", "Поддержание формы"), ("gain", "Набор веса")],
                default="",
                max_length=4,
                verbose_name="Цель",
            ),
        ),
        migrations.AddField(
            model_name="personcard",
            name="exclude_category",
            field=models.ManyToManyField(
                blank=True,
                related_name="personcard",
                to="bood_app.productcategory",
                verbose_name="Исключенные категории продуктов",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product",
                to="bood_app.productcategory",
                verbose_name="Категория",
            ),
        ),
    ]
