# Generated by Django 4.2.7 on 2024-02-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bood_app", "0004_alter_personcard_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personcard",
            name="target",
            field=models.CharField(
                blank=True,
                choices=[("gain", "Набор веса"), ("lose", "Похудение"), ("keep", "Поддержание формы")],
                default="",
                max_length=4,
                verbose_name="Цель",
            ),
        ),
    ]
